### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by carodelafuente** [cartami/project-the-scoop#4]
Exceeds expectations.

Congrats on completing this project! Building a RESTful app on Express has given you the basic fundamentals of a CRUD app. I'm sure now you can see what GET, POST, PUT, DELETE all do. Especially the difference between POST and PUT. (Post creates, put updates). 

Good job implementing yaml too. At first, the data doesn't load until the user posts their own article, but it was still working well regardless. I also liked how you tried making it your own by changing the font-family. 

You're on the way to becoming a great developer, keep it up! 👍

**Comment by cartami** [comment]
Thank you for taking the time to review my work.
